language: python
python:
    - "3.9"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio run -d examples/01
    - platformio run -d examples/02

